/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeusEventosRouteImport } from './routes/_authenticated/meus-eventos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as EventosNovoRouteImport } from './routes/eventos.novo'
import { Route as MentoresSlugRouteImport } from './routes/mentores.$slug'
import { Route as MentoriasIndexRouteImport } from './routes/mentorias.index'
import { Route as MentoriasIdRouteImport } from './routes/mentorias.$id'
import { Route as MentoriasNovaRouteImport } from './routes/mentorias.nova'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as AuthenticatedAdminMensagensRouteImport } from './routes/_authenticated/admin/mensagens'
import { Route as AuthenticatedAdminMentoriasRouteImport } from './routes/_authenticated/admin/mentorias'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeusEventosRoute =
  AuthenticatedMeusEventosRouteImport.update({
    id: '/meus-eventos',
    path: '/meus-eventos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosNovoRoute = EventosNovoRouteImport.update({
  id: '/eventos/novo',
  path: '/eventos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoresSlugRoute = MentoresSlugRouteImport.update({
  id: '/mentores/$slug',
  path: '/mentores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasIndexRoute = MentoriasIndexRouteImport.update({
  id: '/mentorias/',
  path: '/mentorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasIdRoute = MentoriasIdRouteImport.update({
  id: '/mentorias/$id',
  path: '/mentorias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasNovaRoute = MentoriasNovaRouteImport.update({
  id: '/mentorias/nova',
  path: '/mentorias/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensagensRoute =
  AuthenticatedAdminMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMentoriasRoute =
  AuthenticatedAdminMentoriasRouteImport.update({
    id: '/mentorias',
    path: '/mentorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-eventos': typeof AuthenticatedMeusEventosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/eventos/$id': typeof EventosIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mentores/$slug': typeof MentoresSlugRoute
  '/mentorias/$id': typeof MentoriasIdRoute
  '/mentorias/nova': typeof MentoriasNovaRoute
  '/eventos/': typeof EventosIndexRoute
  '/mentorias/': typeof MentoriasIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-eventos': typeof AuthenticatedMeusEventosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/eventos/$id': typeof EventosIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mentores/$slug': typeof MentoresSlugRoute
  '/mentorias/$id': typeof MentoriasIdRoute
  '/mentorias/nova': typeof MentoriasNovaRoute
  '/eventos': typeof EventosIndexRoute
  '/mentorias': typeof MentoriasIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meus-eventos': typeof AuthenticatedMeusEventosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/eventos/$id': typeof EventosIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mentores/$slug': typeof MentoresSlugRoute
  '/mentorias/$id': typeof MentoriasIdRoute
  '/mentorias/nova': typeof MentoriasNovaRoute
  '/eventos/': typeof EventosIndexRoute
  '/mentorias/': typeof MentoriasIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/_authenticated/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/dashboard'
    | '/meus-eventos'
    | '/perfil'
    | '/eventos/$id'
    | '/eventos/novo'
    | '/mentores/$slug'
    | '/mentorias/$id'
    | '/mentorias/nova'
    | '/eventos/'
    | '/mentorias/'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/mensagens'
    | '/admin/mentorias'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/dashboard'
    | '/meus-eventos'
    | '/perfil'
    | '/eventos/$id'
    | '/eventos/novo'
    | '/mentores/$slug'
    | '/mentorias/$id'
    | '/mentorias/nova'
    | '/eventos'
    | '/mentorias'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/mensagens'
    | '/admin/mentorias'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/meus-eventos'
    | '/_authenticated/perfil'
    | '/eventos/$id'
    | '/eventos/novo'
    | '/mentores/$slug'
    | '/mentorias/$id'
    | '/mentorias/nova'
    | '/eventos/'
    | '/mentorias/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/mensagens'
    | '/_authenticated/admin/mentorias'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  EventosIdRoute: typeof EventosIdRoute
  EventosNovoRoute: typeof EventosNovoRoute
  MentoresSlugRoute: typeof MentoresSlugRoute
  MentoriasIdRoute: typeof MentoriasIdRoute
  MentoriasNovaRoute: typeof MentoriasNovaRoute
  EventosIndexRoute: typeof EventosIndexRoute
  MentoriasIndexRoute: typeof MentoriasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meus-eventos': {
      id: '/_authenticated/meus-eventos'
      path: '/meus-eventos'
      fullPath: '/meus-eventos'
      preLoaderRoute: typeof AuthenticatedMeusEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/novo': {
      id: '/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof EventosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentores/$slug': {
      id: '/mentores/$slug'
      path: '/mentores/$slug'
      fullPath: '/mentores/$slug'
      preLoaderRoute: typeof MentoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias/': {
      id: '/mentorias/'
      path: '/mentorias'
      fullPath: '/mentorias/'
      preLoaderRoute: typeof MentoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias/$id': {
      id: '/mentorias/$id'
      path: '/mentorias/$id'
      fullPath: '/mentorias/$id'
      preLoaderRoute: typeof MentoriasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias/nova': {
      id: '/mentorias/nova'
      path: '/mentorias/nova'
      fullPath: '/mentorias/nova'
      preLoaderRoute: typeof MentoriasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensagens': {
      id: '/_authenticated/admin/mensagens'
      path: '/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AuthenticatedAdminMensagensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mentorias': {
      id: '/_authenticated/admin/mentorias'
      path: '/mentorias'
      fullPath: '/admin/mentorias'
      preLoaderRoute: typeof AuthenticatedAdminMentoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminMensagensRoute: typeof AuthenticatedAdminMensagensRoute
  AuthenticatedAdminMentoriasRoute: typeof AuthenticatedAdminMentoriasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminMensagensRoute: AuthenticatedAdminMensagensRoute,
  AuthenticatedAdminMentoriasRoute: AuthenticatedAdminMentoriasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeusEventosRoute: typeof AuthenticatedMeusEventosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeusEventosRoute: AuthenticatedMeusEventosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  EventosIdRoute: EventosIdRoute,
  EventosNovoRoute: EventosNovoRoute,
  MentoresSlugRoute: MentoresSlugRoute,
  MentoriasIdRoute: MentoriasIdRoute,
  MentoriasNovaRoute: MentoriasNovaRoute,
  EventosIndexRoute: EventosIndexRoute,
  MentoriasIndexRoute: MentoriasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
