-- Ensure anon/authenticated can execute has_role() from within RLS policies on public tables.
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO anon, authenticated;

-- Seed mentores (matches slugs referenced by the seeded eventos/mentorias).
INSERT INTO public.mentores (slug, nome, foto_url, crn, especialidade, bio, curriculo, formacao, areas_atuacao, cidade, estado, instagram, linkedin, site) VALUES
('ana-ribeiro','Dra. Ana Ribeiro','https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80','CRN-3 12345','Nutrição Clínica','Nutricionista clínica com mais de 15 anos de experiência em condutas baseadas em evidências e atendimento hospitalar.','Doutora em Ciências pela USP. Coordenadora de nutrição em hospital de alta complexidade. Autora de capítulos em livros de nutrição clínica.','Doutorado — USP · Mestrado em Nutrição Clínica — UNIFESP · Graduação — USP',ARRAY['clinica','hospitalar'],'São Paulo','SP','https://instagram.com/draanaribeiro','https://linkedin.com/in/anaribeiro','https://anaribeiro.com.br'),
('lucas-menezes','Prof. Lucas Menezes','https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=600&q=80','CRN-4 22987','Nutrição Esportiva','Consultor de atletas de endurance e força. Palestrante em congressos nacionais e internacionais de nutrição esportiva.','Mestre em Nutrição Esportiva. Consultor de equipes olímpicas brasileiras. 10+ anos formando profissionais na área.','Mestrado — UFRJ · Graduação — UERJ',ARRAY['esporte'],'Rio de Janeiro','RJ','https://instagram.com/proflucasmenezes','https://linkedin.com/in/lucasmenezes',NULL),
('camila-souza','Dra. Camila Souza','https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80','CRN-9 33421','Saúde da Mulher','Nutricionista dedicada à saúde da mulher em todas as fases: ciclo menstrual, gestação, climatério e menopausa.','Especialista em Nutrição Funcional e Endocrinológica. Atende consultório particular em BH e ministra cursos nacionais.','Especialização em Nutrição Endócrina — VP · Graduação — UFMG',ARRAY['saude-mulher','materno-infantil'],'Belo Horizonte','MG','https://instagram.com/dracamilasouza',NULL,'https://camilasouza.com.br'),
('paula-andrade','Nutri. Paula Andrade','https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80','CRN-3 45678','Gestão de UAN','Nutricionista de UAN com foco em processos, custos e liderança de equipes.','MBA em Gestão de Serviços de Alimentação. Consultora de redes de restaurantes coletivos.','MBA — FGV · Graduação — USP',ARRAY['uan','gestao-marketing'],'São Paulo','SP','https://instagram.com/paulaandrade.uan','https://linkedin.com/in/paulaandrade',NULL),
('isadora-liberato','Nutri. Isadora Liberato','https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80','CRN-3 55123','Gestão & Marketing para Nutricionistas','Ajuda nutricionistas a construírem consultórios de sucesso, do primeiro atendimento à agenda cheia.','Mentora de +500 nutricionistas. Criadora do programa Consultório de Sucesso.','Especialização em Marketing Digital — ESPM · Graduação — Mackenzie',ARRAY['gestao-marketing'],'São Paulo','SP','https://instagram.com/isadoraliberato','https://linkedin.com/in/isadoraliberato','https://isadoraliberato.com'),
('marina-costa','Dra. Marina Costa','https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=600&q=80','CRN-2 66234','Materno-Infantil','Especialista em nutrição materno-infantil, com atuação em pré-natal, lactação e introdução alimentar.','Doutora em Ciências da Saúde. Autora de artigos em revistas indexadas de nutrição pediátrica.','Doutorado — UFRGS · Graduação — UFRGS',ARRAY['materno-infantil'],'Porto Alegre','RS','https://instagram.com/dramarinacosta','https://linkedin.com/in/marinacosta',NULL),
('rafael-prado','Dr. Rafael Prado','https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80','CRN-8 77890','Nutrição Clínica Funcional','Referência em raciocínio clínico avançado e abordagem funcional integrativa.','Pós-graduado em Nutrição Funcional e Fitoterapia. Coordena grupos de mentoria clínica há 8 anos.','Pós — VP · Graduação — PUCPR',ARRAY['clinica'],'Curitiba','PR','https://instagram.com/drrafaelprado','https://linkedin.com/in/rafaelprado','https://rafaelprado.com.br')
ON CONFLICT (slug) DO NOTHING;

-- Seed eventos
INSERT INTO public.eventos (nome, resumo, descricao, local, estado, data, duracao, valor, ministrante, mentor_id, banner_url, modalidade, tipo, area, status)
SELECT * FROM (VALUES
  ('Congresso Brasileiro de Nutrição Clínica','Três dias imersivos com os principais nomes da nutrição clínica no Brasil.','Atualizações em condutas clínicas, casos práticos e mesas-redondas com pesquisadores de referência.','Centro de Convenções — São Paulo','SP','2026-09-14T09:00:00Z'::timestamptz,'3 dias',890::numeric,'Dra. Ana Ribeiro + convidados',(SELECT id FROM public.mentores WHERE slug='ana-ribeiro'),'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80','presencial'::modalidade,'congresso'::tipo_evento,'clinica'::area_nutricao,'aprovado'::status_validacao),
  ('Workshop de Nutrição Esportiva','Protocolos práticos para atletas de endurance e força.',NULL,'Online','RJ','2026-08-05T19:00:00Z'::timestamptz,'4 horas',0::numeric,'Prof. Lucas Menezes',(SELECT id FROM public.mentores WHERE slug='lucas-menezes'),'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80','online'::modalidade,'workshop'::tipo_evento,'esporte'::area_nutricao,'aprovado'::status_validacao),
  ('Jornada de Saúde da Mulher','Ciclos, hormônios e nutrição em cada fase da vida.',NULL,'Belo Horizonte','MG','2026-10-02T08:30:00Z'::timestamptz,'2 dias',320::numeric,'Dra. Camila Souza',(SELECT id FROM public.mentores WHERE slug='camila-souza'),'https://images.unsplash.com/photo-1494390248081-4e521a5940db?auto=format&fit=crop&w=1200&q=80','presencial'::modalidade,'jornada'::tipo_evento,'saude-mulher'::area_nutricao,'aprovado'::status_validacao),
  ('Curso de UAN na Prática','Gestão de unidades de alimentação e nutrição do zero à liderança.',NULL,'Online','SP','2026-07-22T20:00:00Z'::timestamptz,'12 horas',240::numeric,'Nutri. Paula Andrade',(SELECT id FROM public.mentores WHERE slug='paula-andrade'),'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80','online'::modalidade,'curso'::tipo_evento,'uan'::area_nutricao,'aprovado'::status_validacao)
) AS v(nome,resumo,descricao,local,estado,data,duracao,valor,ministrante,mentor_id,banner_url,modalidade,tipo,area,status)
WHERE NOT EXISTS (SELECT 1 FROM public.eventos LIMIT 1);

-- Seed mentorias
INSERT INTO public.mentorias (nome, resumo, descricao, local, estado, data, duracao, valor, ministrante, mentor_id, banner_url, modalidade, area, status)
SELECT * FROM (VALUES
  ('Mentoria Consultório de Sucesso','Do primeiro atendimento à agenda cheia em 12 semanas.',NULL,'Online','SP','2026-08-01T19:00:00Z'::timestamptz,'12 semanas',1980::numeric,'Nutri. Isadora Liberato',(SELECT id FROM public.mentores WHERE slug='isadora-liberato'),'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80','online'::modalidade,'gestao-marketing'::area_nutricao,'aprovado'::status_validacao),
  ('Mentoria em Nutrição Materno-Infantil','Grupo fechado com estudos de caso semanais.',NULL,'Online','RS','2026-09-10T20:00:00Z'::timestamptz,'8 semanas',1200::numeric,'Dra. Marina Costa',(SELECT id FROM public.mentores WHERE slug='marina-costa'),'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80','online'::modalidade,'materno-infantil'::area_nutricao,'aprovado'::status_validacao),
  ('Grupo de Mentoria Clínica Funcional','Encontros presenciais mensais com raciocínio clínico avançado.',NULL,'Curitiba','PR','2026-08-20T09:00:00Z'::timestamptz,'6 meses',3600::numeric,'Dr. Rafael Prado',(SELECT id FROM public.mentores WHERE slug='rafael-prado'),'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=1200&q=80','presencial'::modalidade,'clinica'::area_nutricao,'aprovado'::status_validacao)
) AS v(nome,resumo,descricao,local,estado,data,duracao,valor,ministrante,mentor_id,banner_url,modalidade,area,status)
WHERE NOT EXISTS (SELECT 1 FROM public.mentorias LIMIT 1);